= regvue
:imagesdir: images
:toc: macro

A modern web-based viewer for FPGA/ASIC register documentation.

https://github.jpl.nasa.gov/pages/regvue/regvue/demo[Demo]

https://github.jpl.nasa.gov/regvue/demos[Additional demos]

toc::[]

== Install on Local Machine

. Download the https://github.jpl.nasa.gov/regvue/regvue/releases[latest release].

. Extract
+
 tar xf regvue-0.1.0.tar.gz
 cd regvue-0.1.0

. Replace `data.json` with your own

. Start a local webserver
+
[source,sh]
----
# Using Python 3
python3 -m http.server 8080

# Using Python 2
python -m SimpleHTTPServer 8080
----

. Open http://localhost:8080

== Generating `data.json`

The `data.json` file uses the Register Description Format as documented in link:schema/register-description-format.adoc[].

== Hosting on GitHub Pages

=== Initial Setup

==== Create the `gh-pages` Branch

[source,sh]
----
git clone <repo-url> gh-pages
cd gh-pages
git checkout --orphan gh-pages # <1>
git rm -rf . # <2>
touch .gitignore # <3>
git add .gitignore
git commit
git push origin gh-pages # <4>
cd ..
rm -rf gh-pages # <5>
----
<1> The `--orphan` option creates a new branch without a parent commit.
<2> The `checkout --orphan` command doesn't remove anything from the working copy so we need to do it manually.
<3> Create a dummy file so we have something to commit.
<4> This adds the branch to the upstream repository on GitHub.
<5> Now that we've created and published the `gh-pages` branch we no longer need the local repository.

==== Enable GitHub Pages

. Go to the GitHub Enterprise repository page.
. Click the "Settings" tab
. For the GitHub Pages Source, select 'gh-pages branch'

=== Publish

Clone the repository and checkout the `gh-pages` branch

[source,sh]
----
git clone --branch gh-pages <repo> gh-pages
cd gh-pages
----

Install `regvue` (if not already installed or if upgrading)

[source,sh]
----
rm -rf regvue # <1>
mkdir regvue
tar xf regvue-0.1.0.tar.gz --strip-components 1 -C regvue # <2>
----
<1> Remove existing `regvue` (if any)
<2> Extract the https://github.jpl.nasa.gov/regvue/regvue/releases[latest release] to the `regvue` directory

Update `data.json`

[source,sh]
----
cp path/to/my_design.json regvue/data.json
----

Add, commit, and push the changes

[source,sh]
----
git add . # <1>
git commit --quiet --amend --message "Publish gh-pages" # <2>
git push --force # <3>
----
<1> Add everything
<2> Keeping a history of large auto-generated HTML documents can unnecessarily increase repository size.
The `--amend` option solves this by overwriting the current commit instead of creating a new one.
<3> Since `commit --amend` rewrites history, a force push is needed.

=== View

The `regvue` app is now availble at `\https://github.jpl.nasa.gov/pages/<organization>/<repository>/regvue`.
