= regvue
:imagesdir: images
:toc: macro

A modern web-based viewer for FPGA/ASIC register documentation.

toc::[]

== Demos

* https://github.jpl.nasa.gov/pages/regvue/regvue/demo[Basic demo]
* https://github.jpl.nasa.gov/regvue/demos[Additional demos]

== Generate the Register Description

Regvue obtains register information from the Register Description Format documented in link:schema/register-description-format.adoc[].

This format can be generated by the following register automation tools:

* https://github.jpl.nasa.gov/rstern-org/reggen[reggen]
* https://github.jpl.nasa.gov/jfve/register-translator[Register Translator]
* https://github.com/rfdonnelly/svd2rdf[svd2rdf]

== Install Regvue

Regvue is a frontend web application.
It runs entirely in the browser.
It only needs a basic static web server to run.

The preferred hosting method is via GitHub Pages.
See the link:docs/install.adoc[install documentation] for more details.

== Upgrade Regvue

Existing GitHub Pages deployments of Regvue are easily upgraded with the link:scripts/upgrade[upgrade script].

[source,sh]
.Example: Upgrade the https://github.jpl.nasa.gov/pages/regvue/regvue/demo[Regvue demo]
----
scripts/upgrade --deployment-repository git@github.jpl.nasa.gov:regvue/regvue.git --deployment-path demo
----

[source,sh]
.Example: Upgrade the https://github.jpl.nasa.gov/pages/regvue/ece[ECE deployment]
----
scripts/upgrade --deployment-repository git@github.jpl.nasa.gov:regvue/ece.git --deployment-path ""
----
