= regvue
:imagesdir: images
:toc: macro

:latest_deployment: v0.5
:deployment_url: https://github.jpl.nasa.gov/pages/regvue/regvue/{latest_deployment}
:demo_register_description: https://github.jpl.nasa.gov/pages/regvue/regvue/demo/data.json

A modern web-based viewer for FPGA/ASIC register documentation.

toc::[]

== Demos

* {deployment_url}/#?data={demo_register_description}[Basic demo]
* https://github.jpl.nasa.gov/regvue/demos[Additional demos]

== Generate the Register Description

Regvue obtains register information from the Register Description Format documented in link:schema/register-description-format.adoc[].

This format can be generated by the following register automation tools:

* https://github.jpl.nasa.gov/rstern-org/reggen[reggen]
* https://github.jpl.nasa.gov/jfve/register-translator[Register Translator]
* https://github.com/rfdonnelly/svd2rdf[svd2rdf]

== Install Regvue

The preferred method of installing Regvue is to not install it at all.
Instead, use an existing deployment of Regvue managed by the Regvue team.

The latest deployment is {deployment_url}

== Load a Register Description

Register descriptions can be loaded via the filesystem or via a URL.

=== Via the Filesystem

Open Regvue and and load a register descriptions by dragging-and-dropping a register description JSON into Regvue or by using the file open dialog.

=== Via a URL (Preferred)

URLs can be created that automatically load a hosted register description into Regvue.

For example,

* the {latest_deployment} deployment: {deployment_url}

* and the demo register description: {demo_register_description}

* can be paired as: {deployment_url}/#?data={demo_register_description}