= Install and Upgrade Regvue
:toc:

Regvue is a frontend web application.
It runs entirely in the browser.
It only needs a basic static web server to run.

NOTE: Because Regvue loads external content (the register description JSON), it cannot be run via the `file://` protocol.
It must be run via the `http://` or `https://` protocols.

Installing Regvue is as simple as copying it to a static web hosting service.

== Host on GitHub Pages

The preferred host for Regvue is GitHub Pages.
GitHub Pages provides free static file hosting and hosted files are managed via standard Git.

=== Setup GitHub Pages

First, GitHub Pages needs to be setup.

==== Create the `gh-pages` Branch

The recommended way to setup GitHub Pages is via a special `gh-pages` branch.
Create the `gh-pages` branch in an existing repository as follows:

[source,sh]
----
git clone <repo-url> gh-pages
cd gh-pages
git checkout --orphan gh-pages # <1>
git rm -rf . # <2>
touch .gitignore # <3>
git add .gitignore
git commit
git push origin gh-pages # <4>
cd ..
rm -rf gh-pages # <5>
----
<1> The `--orphan` option creates a new branch without a parent commit.
<2> The `checkout --orphan` command doesn't remove anything from the working copy so we need to do it manually.
<3> Create a dummy file so we have something to commit.
<4> This adds the branch to the upstream repository on GitHub.
<5> Now that we've created and published the `gh-pages` branch we no longer need the local repository.

==== Enable GitHub Pages

. Go to your GitHub Enterprise repository page.
. Click the "Settings" tab
. For the GitHub Pages Source, select 'gh-pages branch'

=== Install Regvue

Clone the `gh-pages` branch:

[source,sh]
----
git clone --branch gh-pages <repo> gh-pages
cd gh-pages
----

Download the https://github.jpl.nasa.gov/regvue/regvue/releases[latest release].

Extract `regvue`:

[source,sh]
----
mkdir regvue
tar xf regvue-0.1.0.tar.gz --strip-components 1 -C regvue # <1>
----
<1> Extract the https://github.jpl.nasa.gov/regvue/regvue/releases[latest release] to the `regvue` directory

Replace `data.json` with your own link:../schema/register-description-format.adoc[Register Description Format JSON]:

[source,sh]
----
cp path/to/my_design.json regvue/data.json
----

Add, commit, and push the changes:

[source,sh]
----
git add . # <1>
git commit --quiet --amend --message "Publish gh-pages" # <2>
git push --force # <3>
----
<1> Add everything
<2> Keeping a history of large auto-generated HTML documents can unnecessarily increase repository size.
The `--amend` option solves this by overwriting the current commit instead of creating a new one.
<3> Since `commit --amend` rewrites history, a force push is needed.

=== View

The `regvue` app is now availble at `\https://github.jpl.nasa.gov/pages/<organization>/<repository>/regvue`.

== Run on Local Machine

It is also possible to run Regvue on your local machine.
All you need is a static web server.
Most popular scripting languages like Python come with a basic static web server.

Download the https://github.jpl.nasa.gov/regvue/regvue/releases[latest release].

Extract `regvue`:

[source,sh]
----
tar xf regvue-0.1.0.tar.gz
cd regvue-0.1.0
----

Replace `data.json` with your own link:../schema/register-description-format.adoc[Register Description Format JSON]:

[source,sh]
----
cp path/to/my_design.json data.json
----

Start a local webserver:

[source,sh]
----
# Using Python 3
python3 -m http.server 8080

# Using Python 2
python -m SimpleHTTPServer 8080
----

Open http://localhost:8080

== Deploy Script

The link:scripts/deploy[deploy script] automates creating new or upgrade existing deployments on GitHub Pages.
To use the deploy script, you must have the https://cli.github.com/[GitHub CLI] installed and it must be authenticated to your GitHub instance.

=== Examples

Upgrade the self-hosted deployment at `https://github.jpl.nasa.gov/pages/org/repo/regvue` to the latest version.

[source,sh]
----
scripts/deploy \
    --deployment-repository https://github.jpl.nasa.gov/org/repo \
    --deployment-path regvue \
    --release latest
----

Upgrade the official UAT deployment to version v1.1.4.

[source,sh]
----
scripts/deploy \
    --deployment-repository https://github.jpl.nasa.gov/regvue/regvue \
    --deployment-path uat \
    --release v1.1.4
----

Create an official v1.1.4 deployment.

[source,sh]
----
scripts/deploy \
    --deployment-repository https://github.jpl.nasa.gov/regvue/regvue \
    --deployment-path v1.1.4 \
    --release v1.1.4
----
