= Create a Release
:toc:

== Update the Changelog

Update `CHANGELOG.md`.

 git add CHANGELOG.md
 git commit

== Bump the Version

Increment the version according to https://semver.org/[Semantic Versioning 2] which is basically:

* Breaking changes => increment major version
* Backwards compatible feature additions => increment minor version
* Bug fixes only => increment patch version

[source,json]
.app/package.json
----
  "version": "$version",
----

 (cd app; npm install) # update package-lock.json
 git add app/package.json app/package-lock.json
 git commit
 git push

== Create a Tag

 git tag $tag
 git push origin $tag

== Create the Release Package from Fresh Clone

 git clone $repo build
 cd build
 git checkout $tag
 cd app
 npm install
 npm run build
 mv dist regvue-$version
 tar cf regvue-$version.tar.gz regvue-$version

== Create the GitHub Release

Extract relevant portion of `CHANGELOG.md` into `release_notes.md`.

 gh release create $tag --title "$tag - $summary" -F release_notes.md regvue-$version.tar.gz
