= Schema Changlog

== Regvue Versions and Schema Versions

* Regvue v0.x uses schema v0.2
* Regvue v1.x uses schema v1

== Changes from schema v0.x to schema v1

=== Breaking Changes

* The value of the `version` property on the Schema object must be "v1".
+
Previously, this value was required to be "v0.2".

* Undefined properties are now errors
+
Previously, if an RDF JSON had a property that wasn't in the RDF JSON Schema, it would be silently ignored.
In Regvue v1.0 (schema v1), this is now an error.
+
This is especially relevant to the removal of the BlockElement `addr` property from schema v0.x.
JSON generated to schema v0.x will likely contain the `addr` property.
The `addr` property will need to be removed to validate against schema v1.

* The `display_name` property has been renamed to `desc`.

* The link:register-description-format.adoc#root-object[Root] object `desc` property is now required
+
Previously, this was called `display_name` and it was optional for the Root object.
In Regvue v1.0 (schema v1), a missing Root `desc` property is now an error.

* The `size` property in the MemoryElement object is now required
+
Previously, this was optional.
In Regvue v1.0 (schema v1), a missing MemoryElement `size` property is now an error.

== Changes made in schema v0.x

All of these changes were made in a backwards compatible way.

=== Removed

* Removed `name` property from the Root object
+
This was never officially supported or documented but was shown in the examples in the schema docs.
It was used during experimentation with manual merge of RDF JSONs.
It was superseded by Regvue include support.

* Removed the `addr` property on Element objects
+
The `element.addr` property is no longer used.
The address is now calculated dynamically using the `element.offset` property.
The presence of the `element.addr` property will be made an error in Regvue v1.0 (schema v1)
See also https://github.jpl.nasa.gov/regvue/regvue/issues/80[regvue/regvue#80] and https://github.jpl.nasa.gov/regvue/regvue/issues/162[regvue/regvue#162].

=== Added

* Added the optional `doc` property to the link:register-description-format.adoc#root-object[Root] object
* Added the optional `expanded` property to the link:register-description-format.adoc#root-object[Root] object
* Added the optional `data_width` and `default_reset` properties to the link:register-description-format.adoc#root-object[Root] object

* Added string as a value type for the link:register-description-format.adoc#element-objects[Element] `offset` property
** TODO: Confirm this is implemented.
** TODO: Schema currently allows hex values only.  Also accept bin and dec just like reset.  Basically, anything BigInt can parse, offset string scalars should support.

* Added the optional `data_width` and `default_reset` properties to link:register-description-format.adoc#block-element-objects[BlockElement] objects
* Added the `links`, `version`, and `display_name` properties to the link:register-description-format.adoc#block-element-objects[BlockElement] object type.
+
Previously, these properties only existed on the link:register-description-format.adoc#root-object[Root] object.

* Added string as a value type for the Field `reset` property
* Added link:register-description-format.adoc#reset-objects[Reset object] as a value type for the Field `reset` property (to support multiple resets)

* Added the link:register-description-format.adoc#include-element-objects[IncludeElement] type

* Added support to Regvue for the link:register-description-format.adoc#field-objects[Field] `enum` property
+
This is not actually a schema change since the schema already supported this.
The change here is that Regvue now supports this.

* Added string as a value type for the link:register-description-format.adoc#enum-value-objects[EnumValue] `value` property
** TODO: Add a pattern to the schema for the EnumValue `value` property
** TODO: Make sure bin, dec, hex string values are supported.

=== Changed

* Changed the link:register-description-format.adoc#element-objects[Element] `offset` property from required to optional.
+
NOTE: The `offset` property is still required for link:register-description-format.adoc#register-element-objects[RegisterElement] objects but is not longer required for the other Element object types (i.e. BlockElement, MemoryElement, IncludeElement)
