= Register Description File
:sectnums:
:toc:
:toclevels: 4

Register Explorer uses a register description file to provide a hierarchical view into the design under test (DUT).

The register description files use YAML syntax, and must have either a `.yml` or `.yaml` file extension.
If you're new to YAML and want to learn more, see "https://learnxinyminutes.com/docs/yaml/Learn[YAML in Y minutes]."

Register description files are intended to be generated via a register automation solution.

[source,yaml]
.Small complete example
----
schema:
  name: register-description-format
  version: v0.2

root:
  name: example
  display_name: Example Design
  version: v1.0
  links:
    GitHub: https://github.com/org/repo
  children:
    - blk0

elements:
  blk0:
    type: blk
    id: blk0
    name: blk0
    children:
      - blk0.reg0
      - blk0.reg1

  blk0.reg0:
    id: blk0.reg0
    type: reg
    name: reg0
    addr: 0x0
    offset: 0x0
    doc: An example register.
    fields:
      - name: rsvd
        lsb: 5
        nbits: 28
        access: rw
        doc: A reserved field.
      - name: command
        lsb: 0
        nbits: 4
        access: rw
        doc: The command to execute.
        enum:
          - name: START
            value: 0x5
            doc: Starts the operation.
          - name: STOP
            value: 0xA
            doc: Stops the operation.

  blk0.reg1:
    type: reg
    id: blk0.reg1
    name: reg1
    data_width: 16
    addr: 0x4
    offset: 0x4
    fields:
      - name: f0
        lsb: 0
        nbits: 16
        access: ro
        reset: 0x0
----

== Root Object

The root object contains the following properties:

* `schema` -- Specifies schema version information
* `root` -- Specifies the top level design elements
* `elements` -- Defines all design elements and their relationships

== `schema` Property

The `schema` property specifies the version of the register schema used by the document.

[source,yaml]
.`schema` snippet
----
schema:
  name: register-description-format
  version: v0.2
----

== Element IDs

Element IDs uniquely identify elements.

=== Hierarchy

By convention, hierarchy is denoted via the `.` character.

For example, the element ID `regs.blk0.reg0` has the following hierarchy:

[listing]
----
regs
└── blk0
    └── reg0
----

== `root` Property

The `root` property specifies the top level as a block element.
See also <<block-elements>>.

The `root` property supports the following additional keys:

* `display_name` -- The design name intended for human consumption.
* `data_width` -- The size of register elements in number of bits.
Applies to all children unless overwritten by a child element.
If absent defaults to 32.

[source,yaml]
.`root` snippet
----
root:
  name: example
  display_name: Example Design
  version: v1.0
  links:
    GitHub: https://github.com/org/repo
  children:
    - element0
    - element1
----

== `elements` Property

The `elements` property defines all design elements and their hierarchy.

Elements are specified in a flat map indexed by element ID.
Elements can reference other elements by their element ID to create a describe a tree structure.

There are three element types.

* Block (`blk`)
* Register (`reg`)
* Memory (`mem`)

The element type is specified via the `type` property.

All elements support the following keys:

* `id` -- A copy of the element ID.
Must be unique.
One convention is to concatenate hierarchical element names (e.g. `blk.sub_blk.reg`).
Required.
* `name` -- The name of the element.
Must be a valid C language identifier.
Meant for human and machine consumption.
Required.
* `display_name` -- The name of the element meant for human consumption.
Optional.
* `type` -- One of `blk`, `mem`, or `reg`
Required.
* `addr` -- The address (bytes) of the element relative to the root.
Required.
* `offset`: The offset (bytes) of the element relative to its parent.
Required.
* `doc` -- Documentation for the element.
Supports HTML.
Optional.
* `data_width` -- Specifies the size of register elements in number of bits.
Applies to all children unless overwritten by a child element.
Optional.

[#block-elements]
=== Block Elements (`blk`)

Block elements are a grouping of other elements.
They are identified as blocks via the `type: blk` key-value pair.
Block elements can contain `reg`, `mem`, and other `blk` elements.
They have the following keys:

* `type`: `blk`
* `version` -- the block version
Optional.
* `links` -- relevant links (text/URI pairs)
Optional.
* `size`: The size (bytes) of the block.
Optional.
* `children`: A sequence of element IDs.

[source,yaml]
.Block element example
----
block0:
  id: block0
  name: block0
  type: blk
  offset: 0x0
  size: 0x1000
  children:
    - block1
    - reg0
    - mem0
----

=== Register Elements (`reg`)

Register elements describe 32-bit hardware registers.
They are identified as registers via the `type: reg` key-value pair.
They have the following keys:

* `type`: `reg`
* `fields`: A sequence of Field objects.

==== Field Objects

Field objects describe an n-bit register field.
They have the following keys:

* `name`: The name of the field.
Required.
* `nbits`: The size of the field in bits.
Required.
* `lsb`: The index of the least significant bit of the field relative to the register.
Required.
* `access`: The software access type of the field.
Required.
* `doc`: The documentation for the field.
Optional.
* `repr`: The default representation.
Default: `hex`.
Optional.
** `bin`: Binary (e.g. `0b0101`)
** `dec`: Decimal (e.g. `5`)
** `hex`: Hexadecimal (e.g. `0x5`)
* `enum`: A sequence of EnumValue objects
Optional.
* `custom_decode`: Custom decode function to apply.
Default: None.
Optional.
* `custom_encode`: Custom decode function to apply.
Default: None.
Optional.

===== EnumValue Objects

Enum value objects describe a single enumerated value.
They have the following keys:

* `name`: The symbolic name of the enumerated value.
Required.
* `value`: The numeric value of the enumerated value.
Required.
* `doc`: The documentation for the enumerated value.
HTML supportted.
Optional.

==== Register Element Example

[source,yaml]
.Register element example
----
blk0.reg0:
  id: blk0.reg0
  type: reg
  name: reg0
  addr: 0x0
  offset: 0x0
  doc: An example register.
  fields:
    - name: rsvd
      lsb: 5
      nbits: 28
      access: rw
      doc: A reserved field.
    - name: command
      lsb: 0
      nbits: 4
      access: rw
      doc: The command to execute.
      enum:
        - name: START
          value: 0x5
          doc: Starts the operation.
        - name: STOP
          value: 0xA
          doc: Stops the operation.
----

=== Memory Elements (`mem`)

Memory elements describe contiguous blocks of memory.
They are identified as memories via the `type: mem` key-value pair.
They have the following keys:

* `type`: `mem`
* `size`: The size (bytes) of the memory.
