= Register Description Format
:sectnums:
:toc:
:toclevels: 4
:sectnumlevels: 5
:sectlinks:
:idprefix:
:idsep: -

:Root: <<root-object,Root>>
:ElementID: <<element-ids,Element ID>>
:Element: <<element-objects,Element>>
:BlockElement: <<block-element-objects,BlockElement>>
:RegisterElement: <<register-element-objects,RegisterElement>>
:MemoryElement: <<memory-element-objects,MemoryElement>>
:IncludeElement: <<include-element-objects,IncludeElement>>

The Register Description Format describes a hierarchical view of a hardware design.
It takes some inspiration from the https://www.keil.com/pack/doc/CMSIS/SVD/html/index.html[CMSIS System View Description].

Register Description Format files use JSON syntax and have a `.json` file extension.
If you're new to JSON and want to learn more, see "https://learnxinyminutes.com/docs/json[Learn JSON in Y minutes]."

Register Description Format files are intended to be generated via a register automation solution.

[source,json]
.Small complete example
----
{
  "schema": {
    "name": "register-description-format",
    "version": "v0.2"
  },
  "root": {
    "display_name": "Example Design",
    "version": "v1.0",
    "links": {
      "GitHub": "https://github.com/org/repo"
    },
    "children": [
      "blk0"
    ]
  },
  "elements": {
    "blk0": {
      "type": "blk",
      "id": "blk0",
      "name": "blk0",
      "children": [
        "blk0.reg0",
        "blk0.reg1"
      ]
    },
    "blk0.reg0": {
      "id": "blk0.reg0",
      "type": "reg",
      "name": "reg0",
      "offset": 0,
      "doc": "An example register.",
      "fields": [
        {
          "name": "rsvd",
          "lsb": 5,
          "nbits": 28,
          "access": "rw",
          "doc": "A reserved field."
        },
        {
          "name": "command",
          "lsb": 0,
          "nbits": 4,
          "access": "rw",
          "doc": "The command to execute.",
          "enum": [
            {
              "name": "START",
              "value": 5,
              "doc": "Starts the operation."
            },
            {
              "name": "STOP",
              "value": 10,
              "doc": "Stops the operation."
            }
          ]
        }
      ]
    },
    "blk0.reg1": {
      "type": "reg",
      "id": "blk0.reg1",
      "name": "reg1",
      "data_width": 16,
      "offset": 4,
      "fields": [
        {
          "name": "f0",
          "lsb": 0,
          "nbits": 16,
          "access": "ro",
          "reset": 0
        }
      ]
    }
  }
}
----

== Document Object

The Doucment object is the document top level object with the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`schema`
|Yes
|<<schema-object,Schema>> object
|Specifies schema versioning information.

a|`root`
|Yes
|<<root-object,Root>> object
|Specifies the top level design element.

a|`elements`
|Yes
|<<elements-object,Elements>> object
|Defines all other design elements and their relationships.
|===

[source,json]
.Document object example
----
{
  "schema": {
    ...
  },
  "root": {
    ...
  },
  "elements": {
    ...
  }
}
----

== Schema Object

The Schema object specifies the version of the register schema used by the document.

[source,yaml]
.Schema object example
----
  {
    "name": "register-description-format",
    "version": "v0.2"
  }
----

The Schema object has the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`name`
|Yes
|string
a|Specifies the name of the schema that the RDF JSON targets.
The value must be `register-description-format`.

a|`version`
|Yes
|string
|Specifies the version of the schema that the RDF JSON targets.
The value must be `v0.2` or `v0.2.x` where `x` is any positive integer.
|===

== Element IDs

Element IDs uniquely identify elements.

=== Hierarchy

By convention, hierarchy is denoted via the `.` character.

For example, the element ID `regs.blk0.reg0` has the following hierarchy:

[listing]
----
regs
└── blk0
    └── reg0
----

== Root Object

The Root object specifies the design top level.

The Root object supports all of the properties of {BlockElement} objects with some differences.

The following {BlockElement} object properties are not valid for the Root object:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`offset`
|n/a
|n/a
|The {BlockElement} `offset` property is not valid in the Root object.

|===

The following optional {BlockElement} object properties are required for the Root object:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`display_name`
|Yes
|string
a|See the {BlockElement} object `display_name` property

|===

=== Root Object Example

[source,json]
----
  {
    "display_name": "Example Design",
    "version": "v1.0",
    "links": {
      "GitHub": "https://github.com/org/repo"
    },
    "children": [
      "element0",
      "element1"
    ]
  }
----

== Elements Object

The Elements object defines all design elements and their hierarchy.
It is a collection of key/value pairs where the keys are <<element-ids>> and the values are {Element} objects.

=== Elements Object Example

[source,json]
----
  {
    "element0": {
      ...
    },
    "element1": {
      ...
    },
    ...
  }
----

== Element Objects

There are four element types.

* {BlockElement}
* {RegisterElement}
* {MemoryElement}
* {IncludeElement}

The element type is specified via the Element `type` property.

All element types support the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`type`
|Yes
|string
a|One of `blk`, `mem`, `reg`, or `include`

a|`id`
|Yes
|string
a|A copy of the {ElementID}.
Must be unique.

a|`name`
|Yes
|string
|The name of the element.
Must be a valid C language identifier.
Meant for human and machine consumption.

a|`display_name`
|No
|string
|The name of the element meant for human consumption.

a|`offset`
|No
|number or string
a|The offset (in bytes) of the element relative to its parent.

[source,json]
.`offset` number example
----
"offset": 4,
----

[source,json]
.`offset` string example
----
"offset": "0x4",
----

a|`doc`
|No
|string
|Documentation for the element.
Supports HTML.

|===

[#block-element-objects]
=== BlockElement Objects

BlockElement objects are a grouping of other {Element} objects.
BlockElement objects can contain `reg`, `mem`, `include`, and other `blk` elements.
They are identified as blocks via the `blk` `type`.

BlockElement objects are {Element} objects with some additional properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`type`
|Yes
|string
a|Value must be `blk`

a|`version`
|No
|string
|The version of the block

a|`links`
|No
|object
a|Relevant links (text/URI pairs)

[source,json]
.`links` example
----
"links": {
  "GitHub": "https://github.com/org/repo",
  "Specification": "https://example.com/spec.docx"
}
----

a|`size`
|No
|number or string
|The size (in bytes) of the block.

a|`children`
|Yes
|array of strings
|An array of element IDs.

a|`data_width`
|No
|number
|Specifies the size of register elements in bits.
Applies to all children unless overwritten by a child element.
Default: 32.
Valid values: 16, 32.

a|`default_reset`
|No
|string
a|The name used for a reset when `field.reset` is specified as a scalar.
Applies to all children unless overwritten by a child element.
Default: `"Default"`.

|===

==== BlockElement Object Example

[source,json]
----
  {
    "type": "blk",
    "id": "block0",
    "name": "block0",
    "offset": 0,
    "children": [
      "block1",
      "reg0",
      "mem0"
    ]
  }
----

[#register-element-objects]
=== RegisterElement Objects

RegisterElement objects describe n-bit hardware registers.
They are identified as registers via the `reg` `type`.

RegisterElement objects are {Element} objects with some additional properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`type`
|Yes
|string
a|Value must be `reg`

a|`fields`
|Yes
|array of <<field-objects,Field>> objects
|The bit fields that make up the register
|===

The following optional {Element} object properties are required for RegisterElement objects:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`offset`
|Yes
|number or string
a|The offset (in bytes) of the element relative to its parent.

[source,json]
.`offset` number example
----
"offset": 4,
----

[source,json]
.`offset` string example
----
"offset": "0x4",
----
|===

==== Field Objects

Field objects describe an n-bit register field.
They have the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`name`
|Yes
|string
|The name of the field.

a|`nbits`
|Yes
|number
|The size of the field in bits.

a|`lsb`
|Yes
|number
|The index of the least significant bit of the field relative to the register.

a|`access`
|Yes
|string
|The software access type of the field.

a|`reset`
|No
|number, string, or <<reset-objects,Reset>> object
a|The reset definition of the field.
Strings values can be binary (`0b` prefix), decimal (no prefix), or hexadecimal (`0x` prefix).
See <<reset-objects>> for the Reset object representation.
If no reset name is specified (i.e. a number or string type is used), the name of the reset will be that specified by the closest `default_reset` property.

a|`doc`
|No
|string
|The documentation for the field.
Supports HTML.

a|`enum`
|No
|array of <<enum-value-objects,EnumValue>> objects
|Provides symbolic representations of the numeric values

|===

The following properties are experimental and are subject to change:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`repr`
|No
|string
a|The default representation.
Default: `hex`.

Valid values:

[cols="1,3"]
!===
!Value !Description
a!`"bin"`
a!Binary (e.g. `Ob0101`)

a!`"dec"`
a!Decimal (e.g. `5`)

a!`"hex"`
a!Hexadecimal (e.g. `0x5`)
!===

a|`custom_decode`
|No
|string
|Custom decode function to apply.
Default: None.

a|`custom_encode`
|No
|string
|Custom decode function to apply.
Default: None.

|===

[#reset-objects]
===== Reset Objects

Reset objects allow specifying a non-default reset name and/or multiple reset names.
They have the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`value`
|Yes
|number or string
|The reset value

a|`resets`
|Yes
|array of strings
|One or more reset names
|===

[source,json]
.Reset object example
----
{
  "value": "0x5",
  "resets": [
    "POR",
    "SW"
  ]
}
----

[#enum-value-objects]
===== EnumValue Objects

EnumValue objects describe a single enumerated value.
They have the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`name`
|Yes
|string
|The symbolic name of the enumerated value.

a|`value`
|Yes
|number or string
|The numeric value of the enumerated value.

a|`doc`
|Yes
|string
|The documentation for the enumerated value.
HTML supported.
|===

==== RegisterElement Object Example

[source,json]
----
  {
    "type": "reg",
    "id": "blk0.reg0",
    "name": "reg0",
    "offset": 0,
    "doc": "An example register.",
    "fields": [
      {
        "name": "rsvd",
        "lsb": 5,
        "nbits": 28,
        "access": "rw",
        "doc": "A reserved field."
      },
      {
        "name": "command",
        "lsb": 0,
        "nbits": 4,
        "access": "rw",
        "doc": "The command to execute.",
        "enum": [
          {
            "name": "START",
            "value": 5,
            "doc": "Starts the operation."
          },
          {
            "name": "STOP",
            "value": 10,
            "doc": "Stops the operation."
          }
        ]
      }
    ]
  }
----

[#memory-element-objects]
=== MemoryElement Objects

MemoryElement objects describe contiguous blocks of memory.
They are identified as registers via the `mem` `type`.

MemoryElement objects are {Element} objects with some additional properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`type`
|Yes
|string
a|Value must be `mem`

a|`size`
|Yes
|number or string
a|The size (in bytes) of the memory.
|===

The following optional {Element} object properties are required for RegisterElement objects:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`offset`
|Yes
|number or string
a|The offset (in bytes) of the element relative to its parent.

[source,json]
.`offset` number example
----
"offset": 4,
----

[source,json]
.`offset` string example
----
"offset": "0x4",
----
|===

[#include-element-objects]
=== IncludeElement Objects

IncludeElement objects are used to include other RDF files.

IncludeElement objects are {Element} objects with some additional properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`type`
|Yes
|string
a|Value must be `include`

a|`offset`
|No
|number or string
a|The offset (in bytes) of the element relative to its parent.

a|`url`
|Yes
|string
|The URL to the RDF JSON to be included.
|===

==== Include Semantics

Includes work by effectively merging the {Root} object of the included JSON into the {IncludeElement} object and changing the {IncludeElement} type to `blk`.
