= Register Description Format
:sectnums:
:toc:
:toclevels: 4
:sectnumlevels: 5
:sectlinks:
:idprefix:
:idsep: -

:Root: <<root-object,Root>>
:ElementID: <<element-ids,Element ID>>
:ElementIDs: <<element-ids,Element IDs>>
:Element: <<element-objects,Element>>
:BlockElement: <<block-element-objects,BlockElement>>
:RegisterElement: <<register-element-objects,RegisterElement>>
:MemoryElement: <<memory-element-objects,MemoryElement>>
:IncludeElement: <<include-element-objects,IncludeElement>>

The Register Description Format describes a hierarchical view of a hardware design.
It takes some inspiration from the https://www.keil.com/pack/doc/CMSIS/SVD/html/index.html[CMSIS System View Description].

Register Description Format files use JSON syntax and have a `.json` file extension.
If you're new to JSON and want to learn more, see "https://learnxinyminutes.com/docs/json[Learn JSON in Y minutes]."

Register Description Format files are intended to be generated via a register automation solution.

[source,json]
.Small complete example
----
{
  "schema": {
    "name": "register-description-format",
    "version": "v1"
  },
  "root": {
    "desc": "Example Design",
    "version": "v1.0",
    "links": [
      { "text": "GitHub", "href": "https://github.com/org/repo" }
    ],
    "children": [
      "blk0"
    ]
  },
  "elements": {
    "blk0": {
      "type": "blk",
      "id": "blk0",
      "name": "blk0",
      "children": [
        "blk0.reg0",
        "blk0.reg1"
      ]
    },
    "blk0.reg0": {
      "id": "blk0.reg0",
      "type": "reg",
      "name": "reg0",
      "offset": "0",
      "doc": "An example register.",
      "fields": [
        {
          "name": "rsvd",
          "lsb": 5,
          "nbits": 28,
          "access": "rw",
          "doc": "A reserved field."
        },
        {
          "name": "command",
          "lsb": 0,
          "nbits": 4,
          "access": "rw",
          "doc": "The command to execute.",
          "enum": [
            {
              "name": "START",
              "value": "5",
              "doc": "Starts the operation."
            },
            {
              "name": "STOP",
              "value": "10",
              "doc": "Stops the operation."
            }
          ]
        }
      ]
    },
    "blk0.reg1": {
      "type": "reg",
      "id": "blk0.reg1",
      "name": "reg1",
      "data_width": 16,
      "offset": "4",
      "fields": [
        {
          "name": "f0",
          "lsb": 0,
          "nbits": 16,
          "access": "ro",
          "reset": "0"
        }
      ]
    }
  }
}
----

== Document Object

The Doucment object is the document top level object with the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`schema`
|Yes
|<<schema-object,Schema>> object
|Specifies schema versioning information.

a|`root`
|Yes
|<<root-object,Root>> object
|Specifies the top level design element.

a|`elements`
|Yes
|<<elements-object,Elements>> object
|Defines all other design elements and their relationships.
|===

[source,json]
.Document object example
----
{
  "schema": {
    ...
  },
  "root": {
    ...
  },
  "elements": {
    ...
  }
}
----

== Schema Object

The Schema object specifies the version of the register schema used by the document.

[source,yaml]
.Schema object example
----
  {
    "name": "register-description-format",
    "version": "v1"
  }
----

The Schema object has the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`name`
|Yes
|string
a|Specifies the name of the schema that the RDF JSON targets.
The value must be `register-description-format`.

a|`version`
|Yes
|string
|Specifies the version of the schema that the RDF JSON targets.
The value must be `v1` or `v1.x` where `x` is any positive integer.
|===

== Element IDs

Element IDs uniquely identify elements.

=== Dot Notation

Element IDs are a joining of the all the element names in the hierarchy with the `.` character.

For example, the following hierarchy of element names has an Element ID of `grandparent.parent.child`.

[listing]
.Hierarchy of element names
----
grandparent
└── parent
    └── child
----

== Root Object

The Root object specifies the design top level.

The Root object has the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`desc`
|Yes
|string
|The name of design.
Meant for humans.

a|`version`
|No
|string
|The version of the design.

a|`links`
|No
|array of <<link-objects,Link>> objects
a|Relevant links to external information

[source,json]
.`links` example
----
"links": [
  { "text": "GitHub", "href": "https://github.com/org/repo" },
  { "text": "Specification", "href": "https://example.com/spec.docx" }
]
----

a|`doc`
|No
|string
|Documentation for the design.
Supports HTML.

a|`children`
|Yes
|array of strings
|An array of child {ElementIDs}.

a|`expanded`
|No
|array of strings
|An array of {ElementIDs} to expand in the home view.

a|`data_width`
|No
|integer
|Specifies the size of register elements in bits.
Recursively applies to all children unless overwritten by a child element.
Default: 32.
Valid values: 16, 32.

a|`default_reset`
|No
|string
a|The name used for a reset when `field.reset` is specified as a scalar.
Recursively applies to all children unless overwritten by a child element.
If no value is specified, it will inherit the closest `default_reset` assigned
to an ancestor element.

|===

=== Root Object Example

[source,json]
----
  {
    "desc": "Example Design",
    "version": "v1.0",
    "links": {
      { "text": "GitHub", "href": "https://github.com/org/repo" }
    },
    "children": [
      "element0",
      "element1"
    ]
  }
----

== Elements Object

The Elements object defines all design elements and their hierarchy.
It is a collection of key/value pairs where the keys are <<element-ids>> and the values are {Element} objects.

=== Elements Object Example

[source,json]
----
  {
    "element0": {
      ...
    },
    "element1": {
      ...
    },
    ...
  }
----

== Element Objects

There are four element types.

* {BlockElement}
* {RegisterElement}
* {MemoryElement}
* {IncludeElement}

The element type is specified via the Element `type` property.

All element types support the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`type`
|Yes
|string
a|One of `blk`, `mem`, `reg`, or `include`

a|`id`
|Yes
|string
a|A copy of the {ElementID}.
Must be unique.

a|`name`
|Yes
|string
|The name of the element.
Must be a valid C language identifier.
Meant for human and machine consumption.

a|`desc`
|No
|string
|The name of the element meant for human consumption.

a|`offset`
|No
|string
a|The offset (in bytes) of the element relative to its parent.
String values can be decimal (e.g. "5") or hexadecimal (e.g. "0x5").

[source,json]
.`offset` example
----
"offset": "0x4",
----

a|`doc`
|No
|string
|Documentation for the element.
Supports HTML.

|===

[#block-element-objects]
=== BlockElement Objects

BlockElement objects are a grouping of other {Element} objects.
BlockElement objects can contain `reg`, `mem`, `include`, and other `blk` elements.
They are identified as blocks via the `blk` `type`.

BlockElement objects are {Element} objects with some additional properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`type`
|Yes
|string
a|Value must be `blk`

a|`version`
|No
|string
|The version of the block

a|`links`
|No
|array of <<link-objects,Link>> objects
a|Relevant links to external information

[source,json]
.`links` example
----
"links": [
  { "text": "GitHub", "href": "https://github.com/org/repo" },
  { "text": "Specification", "href": "https://example.com/spec.docx" }
]
----

a|`size`
|No
|string
|The size (in bytes) of the block.
Values can be decimal (e.g. "5") or hexadecimal (e.g. "0x5").

a|`children`
|Yes
|array of strings
|An array of element IDs.

a|`data_width`
|No
|integer
|Specifies the size of register elements in bits.
Recursively applies to all children unless overwritten by a child element.
Default: 32.
Valid values: 16, 32.

a|`default_reset`
|No
|string
a|The name used for a reset when `field.reset` is specified as a scalar.
Recursively applies to all children unless overwritten by a child element.
Default: `"Default"`.

|===

==== Link Objects

Link objects describe a single text/href pair that link to external information.
They have the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`text`
|Yes
|string
|The link text to display.

a|`href`
|Yes
|string
|The URL that the link points to.
|===

==== BlockElement Object Example

[source,json]
----
  {
    "type": "blk",
    "id": "block0",
    "name": "block0",
    "offset": "0",
    "children": [
      "block1",
      "reg0",
      "mem0"
    ]
  }
----

[#register-element-objects]
=== RegisterElement Objects

RegisterElement objects describe n-bit hardware registers.
They are identified as registers via the `reg` `type`.

RegisterElement objects are {Element} objects with some additional properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`type`
|Yes
|string
a|Value must be `reg`

a|`fields`
|Yes
|array of <<field-objects,Field>> objects
|The bit fields that make up the register
|===

The following optional {Element} object properties are required for RegisterElement objects:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`offset`
|Yes
|string
a|The offset (in bytes) of the element relative to its parent.
String values can be decimal (e.g. "5") or hexadecimal (e.g. "0x5").

[source,json]
.`offset` example
----
"offset": "0x4",
----
|===

==== Field Objects

Field objects describe an n-bit register field.
They have the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`name`
|Yes
|string
|The name of the field.

a|`nbits`
|Yes
|integer
|The size of the field in bits.

a|`lsb`
|Yes
|integer
|The index of the least significant bit of the field relative to the register.

a|`access`
|Yes
|string
|The software access type of the field.

a|`reset`
|No
|string or <<reset-objects,Reset>> object
a|The reset definition of the field.
String values can be binary (`0b` prefix), decimal (no prefix), or hexadecimal (`0x` prefix).
String values can contain unknowns (e.g. "0b1?0", "?", "0xf??d").
See <<reset-objects>> for the Reset object representation.
If no reset name is specified (i.e. a string type is used), the name of the reset will be that specified by the closest `default_reset` property.

a|`doc`
|No
|string
|The documentation for the field.
Supports HTML.

a|`enum`
|No
|array of <<enum-value-objects,EnumValue>> objects
|Provides symbolic representations of the numeric values

|===

The following properties are experimental and are subject to change:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`repr`
|No
|string
a|The default representation.
Default: `hex`.

Valid values:

[cols="1,3"]
!===
!Value !Description
a!`"bin"`
a!Binary (e.g. `Ob0101`)

a!`"dec"`
a!Decimal (e.g. `5`)

a!`"hex"`
a!Hexadecimal (e.g. `0x5`)
!===

a|`custom_decode`
|No
|string
|Custom decode function to apply.
Default: None.

a|`custom_encode`
|No
|string
|Custom decode function to apply.
Default: None.

|===

[#reset-objects]
===== Reset Objects

Reset objects allow specifying a non-default reset name and/or multiple reset names.
They have the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`value`
|Yes
|string
|The reset value
Values can be binary (`0b` prefix), decimal (no prefix), or hexadecimal (`0x` prefix).
Values can contain unknowns (e.g. "0b1?0", "?", "0xf??d").

a|`names`
|Yes
|array of strings
|One or more reset names
|===

[source,json]
.Reset object example
----
{
  "value": "0x5",
  "names": [
    "POR",
    "SW"
  ]
}
----

[#enum-value-objects]
===== EnumValue Objects

EnumValue objects describe a single enumerated value.
They have the following properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`name`
|Yes
|string
|The symbolic name of the enumerated value.

a|`value`
|Yes
|string
|The numeric value of the enumerated value.
Values can be binary (e.g. "0b101"), decimal (e.g. "5") or hexadecimal (e.g. "0x5").

a|`doc`
|Yes
|string
|The documentation for the enumerated value.
HTML supported.
|===

==== RegisterElement Object Example

[source,json]
----
  {
    "type": "reg",
    "id": "blk0.reg0",
    "name": "reg0",
    "offset": "0",
    "doc": "An example register.",
    "fields": [
      {
        "name": "rsvd",
        "lsb": 5,
        "nbits": 28,
        "access": "rw",
        "doc": "A reserved field."
      },
      {
        "name": "command",
        "lsb": 0,
        "nbits": 4,
        "access": "rw",
        "doc": "The command to execute.",
        "enum": [
          {
            "name": "START",
            "value": "5",
            "doc": "Starts the operation."
          },
          {
            "name": "STOP",
            "value": "10",
            "doc": "Stops the operation."
          }
        ]
      }
    ]
  }
----

[#memory-element-objects]
=== MemoryElement Objects

MemoryElement objects describe contiguous blocks of memory.
They are identified as registers via the `mem` `type`.

MemoryElement objects are {Element} objects with some additional properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`type`
|Yes
|string
a|Value must be `mem`

a|`size`
|Yes
|string
a|The size (in bytes) of the memory.
Values can be decimal (e.g. "5") or hexadecimal (e.g. "0x5").
|===

The following optional {Element} object properties are required for RegisterElement objects:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`offset`
|Yes
|string
a|The offset (in bytes) of the element relative to its parent.
Values can be decimal (e.g. "5") or hexadecimal (e.g. "0x5").

[source,json]
.`offset` example
----
"offset": "0x4",
----
|===

[#include-element-objects]
=== IncludeElement Objects

IncludeElement objects are used to include other RDF files.

IncludeElement objects are {Element} objects with some additional properties:

[cols="1,1,1,4"]
|===
|Name |Required |Type |Description

a|`type`
|Yes
|string
a|Value must be `include`

a|`offset`
|No
|string
a|The offset (in bytes) of the element relative to its parent.
Values can be decimal (e.g. "5") or hexadecimal (e.g. "0x5").

a|`url`
|Yes
|string
|The URL to the RDF JSON to be included.
The URL can be absolute (e.g. `\https://example.com/file.json`) or relative (e.g. `file.json`).
Relative URLs are relative to the current JSON document.
For example, if `\https://example.com/path/to/parent/parent.json` includes `child.json`, the expanded path for `child.json` will be `\https://example.com/path/to/parent/child.json`.
|===

==== Include Semantics

Includes work by effectively merging the {Root} object of the included JSON into the {IncludeElement} object and changing the {IncludeElement} type to `blk`.
